"""
SentinelX Live Traffic Monitor

This script reads network traffic flows from a CSV in real-time (as generated by cicflowmeter)
and evaluates them against our 3 detection engines (GraphSAGE, Rule Engine, Isolation Forest).

Usage:
  # Real mode (Ubuntu running cicflowmeter)
  python live_monitor.py --file live_traffic.csv
  
  # Simulator mode (Local testing on existing dataset)
  python live_monitor.py --simulate --file "../dataset/combinenew.csv"
"""

import os
import sys
import time
import argparse
import io
import torch
import numpy as np
import pandas as pd

# Force UTF-8 output on Windows
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# Add module directories to sys.path so their internal imports (like 'import config') work
project_root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.join(project_root, 'zero_day_module'))
sys.path.insert(0, os.path.join(project_root, 'detection_engine'))

from config import MODEL_SAVE_PATH as GRAPHSAGE_MODEL_PATH
from model import GraphSAGEDetector
from graph_construction import build_knn_graph
from rule_engine import RuleEngine
from isolation_forest import AnomalyDetector

# CLI Colors using ANSI
class Colors:
    RED = '\033[91m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    RESET = '\033[0m'

def print_alert(flow_idx, msg, engine, severity="HIGH"):
    print(f"\n{Colors.RED}{Colors.BOLD}[!] ALERT TRIGGERED {Colors.RESET}")
    print(f"{Colors.RED} > Flow #   : {flow_idx}{Colors.RESET}")
    print(f"{Colors.RED} > Engine   : {engine}{Colors.RESET}")
    print(f"{Colors.RED} > Details  : {msg}{Colors.RESET}")
    print(f"{Colors.RED} > Severity : {severity}{Colors.RESET}")
    print("-" * 60)

def load_engines():
    print(f"{Colors.CYAN}[*] Loading SentinelX Detection Engines...{Colors.RESET}")
    
    # 1. Rule Engine
    rules_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'detection_engine', 'rules')
    rule_engine = RuleEngine(rules_dir)
    print(f"    - Rule Engine Loaded ({len(rule_engine.rules)} rules)")
    
    # 2. Isolation Forest (We'll load a quick pretrained one or mock it for demo if not saved)
    # Since we didn't save the IF model in the previous script to a file, 
    # we will initialize a fresh one and train it on a tiny random background set on startup.
    print(f"    - Initializing Isolation Forest... (training on background traffic)")
    if_detector = AnomalyDetector(contamination=0.05)
    
    # Let's load 1000 rows of background traffic to train IF and use for GraphSAGE context
    dataset_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'dataset', 'combinenew.csv')
    df_bg = pd.read_csv(dataset_path, nrows=2000, low_memory=False)
    df_bg.columns = df_bg.columns.str.strip()
    
    # Train IF on background
    if_detector.train(df_bg)
    
    # 3. GraphSAGE
    print(f"    - Loading GraphSAGE Model...")
    drop_cols = ["Label", "BinaryLabel"]
    feature_cols = [c for c in df_bg.columns if c not in drop_cols]
    
    # Calculate global mean/std for scaling (simplified for demo)
    X_bg_raw = df_bg[feature_cols].replace([np.inf, -np.inf], np.nan).fillna(0).values.astype(np.float32)
    scaler_mean = np.mean(X_bg_raw, axis=0)
    scaler_std = np.std(X_bg_raw, axis=0) + 1e-8
    
    # Keep 50 scaled background nodes to build the KNN graph against incoming live traffic
    X_bg_scaled = (X_bg_raw[:50] - scaler_mean) / scaler_std
    y_bg = (df_bg["Label"].astype(str).str.strip().values[:50] != "BENIGN").astype(np.int64)
    
    gs_model = GraphSAGEDetector(in_channels=X_bg_scaled.shape[1])
    try:
        gs_model.load_state_dict(torch.load(GRAPHSAGE_MODEL_PATH, map_location=torch.device('cpu'), weights_only=True))
        gs_model.eval()
        print(f"    - GraphSAGE Loaded successfully.")
    except Exception as e:
        print(f"{Colors.YELLOW}[!] Warning: Could not load GraphSAGE model from {GRAPHSAGE_MODEL_PATH}. Was it trained?{Colors.RESET}")
    
    return rule_engine, if_detector, gs_model, X_bg_scaled, y_bg, scaler_mean, scaler_std, feature_cols

def follow(thefile):
    """Generator that yields new lines in a file like 'tail -f'"""
    thefile.seek(0, 2)
    while True:
        line = thefile.readline()
        if not line:
            time.sleep(0.1)
            continue
        yield line

def simulate_live_feed(filepath, max_rows=200):
    """Simulate live traffic from a CSV. Picks a smart mix of BENIGN + Attack rows."""
    import random
    random.seed(42)
    
    with open(filepath, 'r', encoding='utf-8') as f:
        header = f.readline()
        yield header
        all_lines = f.readlines()
    
    # Pick ~140 BENIGN + ~60 attack rows (to make the demo interesting)
    benign_lines = [l for l in all_lines if l.rstrip().endswith('BENIGN')]
    attack_lines = [l for l in all_lines if not l.rstrip().endswith('BENIGN')]
    
    n_benign = min(140, len(benign_lines))
    n_attack = min(60, len(attack_lines))
    
    selected = random.sample(benign_lines, n_benign) + random.sample(attack_lines, n_attack)
    random.shuffle(selected) # Mix them up
    
    print(f"{Colors.CYAN}[i] Simulator: feeding {len(selected)} flows ({n_benign} benign + {n_attack} attack){Colors.RESET}")
    for line in selected[:max_rows]:
        time.sleep(0.08)  # 80ms per flow
        yield line

def main():
    parser = argparse.ArgumentParser(description="SentinelX Live Monitor")
    parser.add_argument("--file", required=True, help="Path to the CSV file to monitor")
    parser.add_argument("--simulate", action="store_true", help="Simulate live traffic from an existing CSV")
    args = parser.parse_args()
    
    print("\n" + "="*60)
    print(f"{Colors.BOLD}   SENTINELX -- LIVE ZERO-DAY DETECTION MONITOR{Colors.RESET}")
    print("="*60 + "\n")
    
    rule_engine, if_detector, gs_model, X_bg, y_bg, scaler_mean, scaler_std, feature_cols = load_engines()
    
    print(f"\n{Colors.GREEN}[*] SentinelX is Active. Monitoring {args.file} ...{Colors.RESET}\n")
    print("-" * 60)
    
    if args.simulate:
        stream = simulate_live_feed(args.file)
    else:
        # In a real environment, you open the file and follow it
        if not os.path.exists(args.file):
            print(f"File {args.file} not found. Waiting for cicflowmeter to create it...")
            while not os.path.exists(args.file):
                time.sleep(1)
        
        f = open(args.file, 'r', encoding='utf-8')
        header = f.readline() # Skip header
        stream = follow(f)
    
    header_skipped = False
    flow_count = 0
    alert_counts = {"Rule Engine": 0, "Isolation Forest": 0, "GraphSAGE": 0}
    
    # Suppress noisy internal ML prints during live monitoring
    import contextlib
    
    try:
        for line in stream:
            if not header_skipped and "Flow Duration" in line:
                header_skipped = True
                continue
                
            flow_count += 1
            if flow_count % 20 == 0:
                print(f"{Colors.CYAN}[i] Processed {flow_count} flows... Traffic normal.{Colors.RESET}")
                
            try:
                # Parse CSV line
                parts = line.strip().split(',')
                features_raw = []
                for p in parts:
                    try:
                        features_raw.append(float(p))
                    except:
                        pass
                
                if len(features_raw) >= len(feature_cols):
                    features_raw = features_raw[:len(feature_cols)]
                else:
                    continue
                    
                # 1. Rule Engine Evaluation
                flow_dict = {col: val for col, val in zip(feature_cols, features_raw)}
                triggered_rules = rule_engine.evaluate_flow(flow_dict)
                if triggered_rules:
                    for rule in triggered_rules:
                        print_alert(flow_count, f"Signature match: {rule}", "Sigma Rule Engine")
                        alert_counts["Rule Engine"] += 1
                
                # Prepare features for ML
                x_live = np.array([features_raw], dtype=np.float32)
                x_live[np.isinf(x_live)] = 0
                
                # 2. Isolation Forest Evaluation (suppress prints)
                df_live = pd.DataFrame(x_live, columns=feature_cols)
                with contextlib.redirect_stdout(io.StringIO()):
                    is_anomaly = if_detector.predict(df_live).iloc[0]
                if is_anomaly:
                    print_alert(flow_count, "Statistical anomaly detected in flow traffic pattern.", "Isolation Forest", severity="MEDIUM")
                    alert_counts["Isolation Forest"] += 1
                
                # 3. GraphSAGE Evaluation (suppress prints)
                x_live_scaled = (x_live - scaler_mean) / scaler_std
                X_combined = np.vstack([X_bg, x_live_scaled])
                y_combined = np.append(y_bg, [0])
                
                with contextlib.redirect_stdout(io.StringIO()):
                    graph_data = build_knn_graph(X_combined, y_combined, k=3)
                
                with torch.no_grad():
                    logits = gs_model(graph_data.x, graph_data.edge_index)
                    probs = torch.softmax(logits, dim=1)
                    new_node_pred = logits[-1].argmax().item()
                    new_node_conf = probs[-1][1].item()
                    
                    if new_node_pred == 1 and new_node_conf > 0.85:
                        print_alert(flow_count, f"Zero-Day / Unknown Attack structure detected. (Confidence: {new_node_conf*100:.1f}%)", "GraphSAGE", severity="CRITICAL")
                        alert_counts["GraphSAGE"] += 1

            except Exception as e:
                pass

    except KeyboardInterrupt:
        pass
    
    # Print summary
    total_alerts = sum(alert_counts.values())
    print(f"\n{'='*60}")
    print(f"{Colors.BOLD}   MONITORING SESSION COMPLETE{Colors.RESET}")
    print(f"{'='*60}")
    print(f"  Total flows analyzed : {flow_count}")
    print(f"  Total alerts fired   : {total_alerts}")
    print(f"    - Rule Engine      : {alert_counts['Rule Engine']}")
    print(f"    - Isolation Forest : {alert_counts['Isolation Forest']}")
    print(f"    - GraphSAGE        : {alert_counts['GraphSAGE']}")
    print(f"{'='*60}")
    if total_alerts > 0:
        print(f"{Colors.RED}{Colors.BOLD}  [!!] THREATS DETECTED. Immediate investigation recommended.{Colors.RESET}")
    else:
        print(f"{Colors.GREEN}  [OK] No threats detected during this session.{Colors.RESET}")

if __name__ == "__main__":
    main()
