"""
SentinelX Live Traffic Monitor

This script reads network traffic flows from a CSV in real-time (as generated by cicflowmeter)
and evaluates them against our 3 detection engines (GraphSAGE, Rule Engine, Isolation Forest).

Usage:
  # Real mode (Ubuntu running cicflowmeter)
  python live_monitor.py --file live_traffic.csv
  
  # Simulator mode (Local testing on existing dataset)
  python live_monitor.py --simulate --file "../dataset/combinenew.csv"
"""

import os
import sys
import time
import argparse
import io
import torch
import numpy as np
import pandas as pd

# Force UTF-8 output on Windows, but ensure line-buffering so live prints aren't delayed!
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace', line_buffering=True)
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace', line_buffering=True)

# Add module directories to sys.path so their internal imports (like 'import config') work
project_root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.join(project_root, 'zero_day_module'))
sys.path.insert(0, os.path.join(project_root, 'detection_engine'))

from config import MODEL_SAVE_PATH as GRAPHSAGE_MODEL_PATH
from model import GraphSAGEDetector
from graph_construction import build_knn_graph
from rule_engine import RuleEngine
from isolation_forest import AnomalyDetector

# CLI Colors using ANSI
class Colors:
    RED = '\033[91m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    RESET = '\033[0m'

def print_alert(flow_idx, msg, engine, severity="HIGH"):
    print(f"\n{Colors.RED}{Colors.BOLD}[!] ALERT TRIGGERED {Colors.RESET}")
    print(f"{Colors.RED} > Flow #   : {flow_idx}{Colors.RESET}")
    print(f"{Colors.RED} > Engine   : {engine}{Colors.RESET}")
    print(f"{Colors.RED} > Details  : {msg}{Colors.RESET}")
    print(f"{Colors.RED} > Severity : {severity}{Colors.RESET}")
    print("-" * 60)

def load_engines():
    print(f"{Colors.CYAN}[*] Loading SentinelX Detection Engines...{Colors.RESET}")
    
    # 1. Rule Engine
    rules_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'detection_engine', 'rules')
    rule_engine = RuleEngine(rules_dir)
    print(f"    - Rule Engine Loaded ({len(rule_engine.rules)} rules)")
    
    # 2. Isolation Forest (We'll load a quick pretrained one or mock it for demo if not saved)
    # Since we didn't save the IF model in the previous script to a file, 
    # we will initialize a fresh one and train it on a tiny random background set on startup.
    print(f"    - Initializing Isolation Forest... (training on background traffic)")
    if_detector = AnomalyDetector(contamination=0.05)
    
    # Let's load 1000 rows of background traffic to train IF and use for GraphSAGE context
    dataset_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'dataset', 'combinenew.csv')
    df_bg = pd.read_csv(dataset_path, nrows=2000, low_memory=False)
    df_bg.columns = df_bg.columns.str.strip()
    
    # Train IF on background
    if_detector.train(df_bg)
    
    # 3. GraphSAGE
    print(f"    - Loading GraphSAGE Model...")
    drop_cols = ["Label", "BinaryLabel"]
    feature_cols = [c for c in df_bg.columns if c not in drop_cols]
    
    # Calculate global mean/std for scaling (simplified for demo)
    X_bg_raw = df_bg[feature_cols].replace([np.inf, -np.inf], np.nan).fillna(0).values.astype(np.float32)
    scaler_mean = np.mean(X_bg_raw, axis=0)
    scaler_std = np.std(X_bg_raw, axis=0) + 1e-8
    
    # Keep 50 scaled background nodes to build the KNN graph against incoming live traffic
    X_bg_scaled = (X_bg_raw[:50] - scaler_mean) / scaler_std
    y_bg = (df_bg["Label"].astype(str).str.strip().values[:50] != "BENIGN").astype(np.int64)
    
    gs_model = GraphSAGEDetector(in_channels=X_bg_scaled.shape[1])
    try:
        gs_model.load_state_dict(torch.load(GRAPHSAGE_MODEL_PATH, map_location=torch.device('cpu'), weights_only=True))
        gs_model.eval()
        print(f"    - GraphSAGE Loaded successfully.")
    except Exception as e:
        print(f"{Colors.YELLOW}[!] Warning: Could not load GraphSAGE model from {GRAPHSAGE_MODEL_PATH}. Was it trained?{Colors.RESET}")
    
    return rule_engine, if_detector, gs_model, X_bg_scaled, y_bg, scaler_mean, scaler_std, feature_cols

def follow(thefile):
    """Generator that yields new lines in a file like 'tail -f'"""
    thefile.seek(0, 2)
    while True:
        line = thefile.readline()
        if not line:
            time.sleep(0.1)
            continue
        yield line

def simulate_live_feed(filepath, max_rows=200):
    """Simulate live traffic from a CSV. Picks a smart mix of BENIGN + Attack rows."""
    import random
    random.seed(42)
    
    with open(filepath, 'r', encoding='utf-8') as f:
        header = f.readline()
        yield header
        all_lines = f.readlines()
    
    # Pick ~140 BENIGN + ~60 attack rows (to make the demo interesting)
    benign_lines = [l for l in all_lines if l.rstrip().endswith('BENIGN')]
    attack_lines = [l for l in all_lines if not l.rstrip().endswith('BENIGN')]
    
    n_benign = min(140, len(benign_lines))
    n_attack = min(60, len(attack_lines))
    
    selected = random.sample(benign_lines, n_benign) + random.sample(attack_lines, n_attack)
    random.shuffle(selected) # Mix them up
    
    print(f"{Colors.CYAN}[i] Simulator: feeding {len(selected)} flows ({n_benign} benign + {n_attack} attack){Colors.RESET}")
    for line in selected[:max_rows]:
        time.sleep(0.08)  # 80ms per flow
        yield line

def main():
    parser = argparse.ArgumentParser(description="SentinelX Live Monitor")
    parser.add_argument("--file", required=True, help="Path to the CSV file to monitor")
    parser.add_argument("--simulate", action="store_true", help="Simulate live traffic from an existing CSV")
    args = parser.parse_args()
    
    print("\n" + "="*60)
    print(f"{Colors.BOLD}   SENTINELX -- LIVE ZERO-DAY DETECTION MONITOR{Colors.RESET}")
    print("="*60 + "\n")
    
    rule_engine, if_detector, gs_model, X_bg, y_bg, scaler_mean, scaler_std, feature_cols = load_engines()
    
    print(f"\n{Colors.GREEN}[*] SentinelX is Active. Monitoring {args.file} ...{Colors.RESET}\n")
    print("-" * 60)
    
    if args.simulate:
        stream = simulate_live_feed(args.file)
    else:
        # In a real environment, you open the file and follow it
        if not os.path.exists(args.file):
            print(f"File {args.file} not found. Waiting for cicflowmeter to create it...")
            while not os.path.exists(args.file):
                time.sleep(1)
        
        f = open(args.file, 'r', encoding='utf-8')
        header_line = f.readline().strip()
        stream = follow(f)
    
    flow_count = 0
    alert_counts = {"Rule Engine": 0, "Isolation Forest": 0, "GraphSAGE": 0}
    
    # Hardcoded mapping: CIC-IDS2017 feature name -> cicflowmeter CSV column index
    # This was built by comparing the training dataset headers with cicflowmeter output headers
    CICFLOWMETER_COL_MAP = {
        'Destination Port': 3, 'Flow Duration': 6,
        'Total Fwd Packets': 11, 'Total Backward Packets': 12,
        'Total Length of Fwd Packets': 13, 'Total Length of Bwd Packets': 14,
        'Fwd Packet Length Max': 15, 'Fwd Packet Length Min': 16,
        'Fwd Packet Length Mean': 17, 'Fwd Packet Length Std': 18,
        'Bwd Packet Length Max': 19, 'Bwd Packet Length Min': 20,
        'Bwd Packet Length Mean': 21, 'Bwd Packet Length Std': 22,
        'Flow Bytes/s': 7, 'Flow Packets/s': 8,
        'Flow IAT Mean': 32, 'Flow IAT Std': 35,
        'Flow IAT Max': 33, 'Flow IAT Min': 34,
        'Fwd IAT Total': 36, 'Fwd IAT Mean': 39,
        'Fwd IAT Std': 40, 'Fwd IAT Max': 37, 'Fwd IAT Min': 38,
        'Bwd IAT Total': 41, 'Bwd IAT Mean': 44,
        'Bwd IAT Std': 45, 'Bwd IAT Max': 42, 'Bwd IAT Min': 43,
        'Fwd PSH Flags': 46, 'Bwd PSH Flags': 47,
        'Fwd URG Flags': 48, 'Bwd URG Flags': 49,
        'Fwd Header Length': 28, 'Bwd Header Length': 29,
        'Fwd Packets/s': 9, 'Bwd Packets/s': 10,
        'Min Packet Length': 24, 'Max Packet Length': 23,
        'Packet Length Mean': 25, 'Packet Length Std': 26,
        'Packet Length Variance': 27,
        'FIN Flag Count': 50, 'SYN Flag Count': 51,
        'RST Flag Count': 52, 'PSH Flag Count': 53,
        'ACK Flag Count': 54, 'URG Flag Count': 55,
        'CWE Flag Count': 77, 'ECE Flag Count': 56,
        'Down/Up Ratio': 57, 'Average Packet Size': 58,
        'Avg Fwd Segment Size': 75, 'Avg Bwd Segment Size': 76,
        'Fwd Header Length.1': 28,
        'Fwd Avg Bytes/Bulk': 69, 'Fwd Avg Packets/Bulk': 70,
        'Fwd Avg Bulk Rate': 73, 'Bwd Avg Bytes/Bulk': 71,
        'Bwd Avg Packets/Bulk': 72, 'Bwd Avg Bulk Rate': 74,
        'Subflow Fwd Packets': 78, 'Subflow Fwd Bytes': 80,
        'Subflow Bwd Packets': 79, 'Subflow Bwd Bytes': 81,
        'Init_Win_bytes_forward': 59, 'Init_Win_bytes_backward': 60,
        'act_data_pkt_fwd': 31, 'min_seg_size_forward': 30,
        'Active Mean': 63, 'Active Std': 64,
        'Active Max': 61, 'Active Min': 62,
        'Idle Mean': 67, 'Idle Std': 68,
        'Idle Max': 65, 'Idle Min': 66,
    }
    
    # Build the ordered column index list matching our feature_cols order
    col_mapping = []
    if not args.simulate:
        for fc in feature_cols:
            fc_stripped = fc.strip()
            if fc_stripped in CICFLOWMETER_COL_MAP:
                col_mapping.append(CICFLOWMETER_COL_MAP[fc_stripped])
            else:
                col_mapping.append(-1)  # Will default to 0.0
        mapped_count = sum(1 for c in col_mapping if c >= 0)
        print(f"{Colors.GREEN}    - Column mapping: {mapped_count}/{len(feature_cols)} features mapped to cicflowmeter format{Colors.RESET}")
        header_skipped = True
    else:
        header_skipped = False
    
    # Suppress noisy internal ML prints during live monitoring
    import contextlib
    
    try:
        for line in stream:
            if not header_skipped and ("Flow Duration" in line or "flow_duration" in line):
                header_skipped = True
                continue
                
            flow_count += 1
            if flow_count % 20 == 0:
                print(f"{Colors.CYAN}[i] Processed {flow_count} flows... Traffic normal.{Colors.RESET}")
                
            try:
                # Parse CSV line
                parts = line.strip().split(',')
                features_raw = []
                
                if len(col_mapping) == len(feature_cols):
                    # Live mode: use hardcoded column mapping
                    for idx in col_mapping:
                        if idx >= 0 and idx < len(parts):
                            try:
                                features_raw.append(float(parts[idx]))
                            except:
                                features_raw.append(0.0)
                        else:
                            features_raw.append(0.0)
                else:
                    # Simulator mode: fallback (columns already match)
                    for p in parts:
                        try:
                            features_raw.append(float(p))
                        except:
                            pass
                    if len(features_raw) >= len(feature_cols):
                        features_raw = features_raw[:len(feature_cols)]
                    else:
                        continue
                    
                # 1. Rule Engine Evaluation
                flow_dict = {col: val for col, val in zip(feature_cols, features_raw)}
                triggered_rules = rule_engine.evaluate_flow(flow_dict)
                if triggered_rules:
                    for rule in triggered_rules:
                        print_alert(flow_count, f"Signature match: {rule}", "Sigma Rule Engine")
                        alert_counts["Rule Engine"] += 1
                
                # Prepare features for ML
                x_live = np.array([features_raw], dtype=np.float32)
                x_live[np.isinf(x_live)] = 0
                
                # 2. Isolation Forest Evaluation (suppress prints)
                df_live = pd.DataFrame(x_live, columns=feature_cols)
                with contextlib.redirect_stdout(io.StringIO()):
                    is_anomaly = if_detector.predict(df_live).iloc[0]
                if is_anomaly:
                    print_alert(flow_count, "Statistical anomaly detected in flow traffic pattern.", "Isolation Forest", severity="MEDIUM")
                    alert_counts["Isolation Forest"] += 1
                
                # 3. GraphSAGE Evaluation (suppress prints)
                x_live_scaled = (x_live - scaler_mean) / scaler_std
                X_combined = np.vstack([X_bg, x_live_scaled])
                y_combined = np.append(y_bg, [0])
                
                with contextlib.redirect_stdout(io.StringIO()):
                    graph_data = build_knn_graph(X_combined, y_combined, k=3)
                
                with torch.no_grad():
                    logits = gs_model(graph_data.x, graph_data.edge_index)
                    probs = torch.softmax(logits, dim=1)
                    new_node_pred = logits[-1].argmax().item()
                    new_node_conf = probs[-1][1].item()
                    
                    if new_node_pred == 1 and new_node_conf > 0.65:
                        print_alert(flow_count, f"Zero-Day / Unknown Attack structure detected. (Confidence: {new_node_conf*100:.1f}%)", "GraphSAGE", severity="CRITICAL")
                        alert_counts["GraphSAGE"] += 1

            except Exception as e:
                pass

    except KeyboardInterrupt:
        pass
    
    # Print summary
    total_alerts = sum(alert_counts.values())
    print(f"\n{'='*60}")
    print(f"{Colors.BOLD}   MONITORING SESSION COMPLETE{Colors.RESET}")
    print(f"{'='*60}")
    print(f"  Total flows analyzed : {flow_count}")
    print(f"  Total alerts fired   : {total_alerts}")
    print(f"    - Rule Engine      : {alert_counts['Rule Engine']}")
    print(f"    - Isolation Forest : {alert_counts['Isolation Forest']}")
    print(f"    - GraphSAGE        : {alert_counts['GraphSAGE']}")
    print(f"{'='*60}")
    if total_alerts > 0:
        print(f"{Colors.RED}{Colors.BOLD}  [!!] THREATS DETECTED. Immediate investigation recommended.{Colors.RESET}")
    else:
        print(f"{Colors.GREEN}  [OK] No threats detected during this session.{Colors.RESET}")

if __name__ == "__main__":
    main()
